import Footer from "@/components/Shared/Footer/Footer";
import "./globals.css";
import Header from "@/components/Shared/Header/Header";
import localFont from "next/font/local";
import Providers from "./Providers";
import { Toaster } from "react-hot-toast";

const estedadFont = localFont({
  src: [
    {
      path: "..//public/fonts/estedad/woff2/Estedad-Black.woff2",
      weight: "900",
    },
    {
      path: "..//public/fonts/estedad/woff2/Estedad-Bold.woff2",
      weight: "700",
    },
    {
      path: "..//public/fonts/estedad/woff2/Estedad-ExtraBold.woff2",
      weight: "800",
    },
    {
      path: "..//public/fonts/estedad/woff2/Estedad-ExtraLight.woff2",
      weight: "200",
    },
    {
      path: "..//public/fonts/estedad/woff2/Estedad-Light.woff2",
      weight: "300",
    },
    {
      path: "..//public/fonts/estedad/woff2/Estedad-Medium.woff2",
      weight: "500",
    },
    {
      path: "..//public/fonts/estedad/woff2/Estedad-Regular.woff2",
      weight: "400",
    },
    {
      path: "..//public/fonts/estedad/woff2/Estedad-SemiBold.woff2",
      weight: "600",
    },
    {
      path: "..//public/fonts/estedad/woff2/Estedad-Thin.woff2",
      weight: "100",
    },
  ],
  variable: "--font-estedad",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={estedadFont.className}>
        <Toaster />
        <Providers>
          <Header />

          {children}

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
